name = "Yorha Experimental Branch"
author = "RaylaV"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33f28727f5c2ce571def86701c50fbda588ffac28288fcb35a8b2aefb50d241d"

[versions]
forge = "40.2.13"
minecraft = "1.18.2"
